import Head from 'next/head';
import Banner from '../src/components/home/banner';
import Layout from '../src/components/layout';
import Services from '../src/components/home/services';
import Video from "../src/components/home/Video";
import Value from '../src/components/home/values';
import TestimonyVideo from '../src/components/home/Testimony';

export default function Home() {
  return (
    <Layout homePage={true}>
      <Head>
        <title>Palazzio Nail Lounge</title>
        <meta name="nail salon" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <Services />
        <TestimonyVideo />
        {/* <Video /> */}
        <Value />
      </main>
    </Layout>
  );
}
